# Generated by Django 4.1.4 on 2022-12-26 08:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(5, 'title must be greater than 5 characters')])),
                ('body', models.TextField(validators=[django.core.validators.MinLengthValidator(100, 'blog must be greater than 100 characters')])),
                ('image', models.ImageField(upload_to='blogs_thubnails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
